BCongelao/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BCongelao.Models;

namespace BCongelao.Controllers
{
    public class SalesController : Controller
    {
        private readonly BCongelaoContext _context;

        public SalesController(BCongelaoContext context)
        {
            _context = context;
        }

        // GET: Sales
        public async Task<IActionResult> Index()
        {
            var bCongelaoContext = _context.Sales.Include(s => s.Customer).Include(s => s.SalesPerson).OrderByDescending(o => o.SaleDate).ThenBy(o => o.Customer.CustomerName);
            return View(await bCongelaoContext.ToListAsync());
        }

        // GET: Sales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales
                .Include(s => s.Customer)
                .Include(s => s.SalesPerson)
                .FirstOrDefaultAsync(m => m.SaleId == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // GET: Sales/Create
        public IActionResult Create()
        {
            Sale sale = new Sale();
            sale.Customer = new Customer();
            sale.SaleDate = DateTime.Now;
            ViewData["CustomerId"] = new SelectList(_context.Customers.Where(c => c.StatusCustomer == Models.Enum.StatusCustomer.Activo).OrderBy(c => c.CustomerName), "CustomerId", "CustomerName");
            ViewData["SalesPersonId"] = new SelectList(_context.SalesPersons.Where(s => s.StatusSalesPerson == Models.Enum.StatusSalesPerson.Activo).OrderBy(s => s.SalesPersonName), "SalesPersonId", "SalesPersonName");
            return View(sale);
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SaleId,CustomerId,CustomerDescription,SaleDate,PaymentType,Delivery,SalesPersonId")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                sale.CreatedDate = DateTime.Now;
                sale.StatusSale = Models.Enum.StatusSale.Activa;

                sale.Discount = 0;
                sale.Quantity = 0;
                sale.Paid = 0;
                sale.Total = sale.Delivery;
                sale.TotalNoITBIS = sale.Delivery;

                sale.UserId = User.Identity.Name.ToString();

                if (sale.CustomerId <= 0 && sale.Customer.CustomerName != string.Empty)
                {
                    Customer customer = new Customer();
                    customer.CustomerName = sale.Customer.CustomerName;
                    customer.CreatedDate = DateTime.Now;
                    customer.StatusCustomer = Models.Enum.StatusCustomer.Activo;
                    customer.UserId = User.Identity.Name.ToString();

                    _context.Add(customer);
                    await _context.SaveChangesAsync();
                    sale.CustomerId = customer.CustomerId;
                }
                else
                {
                    sale.Customer = null;
                }

                _context.Add(sale);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers.Where(c => c.StatusCustomer == Models.Enum.StatusCustomer.Activo).OrderBy(c => c.CustomerName), "CustomerId", "CustomerName", sale.CustomerId);
            ViewData["SalesPersonId"] = new SelectList(_context.SalesPersons.Where(s => s.StatusSalesPerson == Models.Enum.StatusSalesPerson.Activo).OrderBy(s => s.SalesPersonName), "SalesPersonId", "SalesPersonName", sale.SalesPersonId);
            ViewData["SaleId"] = sale.SaleId;
            return View(sale);
        }

        // GET: Sales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers.Where(c => c.StatusCustomer == Models.Enum.StatusCustomer.Activo).OrderBy(c => c.CustomerName), "CustomerId", "CustomerName", sale.CustomerId);
            ViewData["SalesPersonId"] = new SelectList(_context.SalesPersons.Where(s => s.StatusSalesPerson == Models.Enum.StatusSalesPerson.Activo).OrderBy(s => s.SalesPersonName), "SalesPersonId", "SalesPersonName", sale.SalesPersonId);
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SaleId,CustomerId,CustomerDescription,SaleDate,Paid,Debt,SalesPersonId,Delivery")] Sale sale)
        {
            if (id != sale.SaleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Sale saleOld = await _context.Sales.FirstOrDefaultAsync(s => s.SaleId == id);
                    if (saleOld.Delivery != sale.Delivery)
                    {
                        decimal _delivery = sale.Delivery - saleOld.Delivery;

                        sale.Total = saleOld.Total + _delivery;
                        sale.TotalNoITBIS = saleOld.TotalNoITBIS + _delivery;
                    }
                    else
                    {
                        sale.Total = saleOld.Total;
                        sale.TotalNoITBIS = saleOld.TotalNoITBIS;
                    }
                    
                    sale.ITBIS = saleOld.ITBIS;
                    sale.Quantity = saleOld.Quantity;
                    sale.PaymentType = saleOld.PaymentType;
                    sale.StatusSale = saleOld.StatusSale;
                    sale.CreatedDate = saleOld.CreatedDate;
                    sale.UserId = saleOld.UserId;
                    sale.Discount = saleOld.Discount;

                    sale.Debt = sale.Total - sale.Paid;

                    decimal _balance = 0;
                    _balance = sale.Paid - saleOld.Paid;

                    Balance balance = await _context.Balances.FirstOrDefaultAsync(d => d.PaymentType == sale.PaymentType);
                    balance.Total += _balance;
                    _context.Update(balance);

                    _context.Entry(saleOld).State = EntityState.Detached; //detach old to update the new

                    _context.Update(sale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaleExists(sale.SaleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers.Where(c => c.StatusCustomer == Models.Enum.StatusCustomer.Activo).OrderBy(c => c.CustomerName), "CustomerId", "CustomerName", sale.CustomerId);
            ViewData["SalesPersonId"] = new SelectList(_context.SalesPersons.Where(s => s.StatusSalesPerson == Models.Enum.StatusSalesPerson.Activo).OrderBy(s => s.SalesPersonName), "SalesPersonId", "SalesPersonName", sale.SalesPersonId);
            return View(sale);
        }

        // GET: Sales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales
                .Include(s => s.Customer)
                .Include(s => s.SalesPerson)
                .FirstOrDefaultAsync(m => m.SaleId == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sale = await _context.Sales.FindAsync(id);

            sale.StatusSale = Models.Enum.StatusSale.Anulada;
            sale.UserId = User.Identity.Name;

            Balance balance = await _context.Balances.FirstOrDefaultAsync(d => d.PaymentType == sale.PaymentType);
            balance.Total -= sale.Paid;
            _context.Update(balance);
            _context.Update(sale);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SaleExists(int id)
        {
            return _context.Sales.Any(e => e.SaleId == id);
        }
    }
}

BCongelao/Controllers/SalesMDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BCongelao.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BCongelao.Controllers
{
    public class SalesMDController : Controller
    {
        private readonly BCongelaoContext _context;

        public SalesMDController(BCongelaoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var bCongelaoContext = _context.Sales.Include(s => s.Customer).Include(s => s.SalesPerson).OrderByDescending(o => o.SaleDate).ThenBy(o => o.Customer.CustomerName);
            return View(await bCongelaoContext.ToListAsync());
        }

        public IActionResult SaleCreate()
        {
            Sale sale = new Sale();
            sale.Customer = new Customer();
            sale.SaleDate = DateTime.Now;
            ViewData["CustomerId"] = new SelectList(_context.Customers.Where(c => c.StatusCustomer == Models.Enum.StatusCustomer.Activo).OrderBy(c => c.CustomerName), "CustomerId", "CustomerName");
            ViewData["SalesPersonId"] = new SelectList(_context.SalesPersons.Where(s => s.StatusSalesPerson == Models.Enum.StatusSalesPerson.Activo).OrderBy(s => s.SalesPersonName), "SalesPersonId", "SalesPersonName");
            return View(sale);
        }

        [HttpPost]
        public async Task<IActionResult> SaleCreate(Sale sale)
        {
            if (ModelState.IsValid)
            {
                //default data
                sale.CreatedDate = DateTime.Now;
                sale.StatusSale = Models.Enum.StatusSale.Activa;

                sale.Quantity = 0;
                sale.Total = sale.Delivery;
                sale.TotalNoITBIS = sale.Delivery;

                sale.UserId = User.Identity.Name.ToString();

                if (sale.CustomerId <= 0 && sale.Customer.CustomerName != string.Empty)
                {
                    Customer customer = new Customer();
                    customer.CustomerName = sale.Customer.CustomerName;
                    customer.CreatedDate = DateTime.Now;
                    customer.StatusCustomer = Models.Enum.StatusCustomer.Activo;
                    customer.UserId = User.Identity.Name.ToString();

                    _context.Add(customer);
                    await _context.SaveChangesAsync();
                    sale.CustomerId = customer.CustomerId;
                }
                else
                {
                    sale.Customer = null;
                }

                //each sale details, change sale amounts
                //_context.Sales.Add(sale);
                //await _context.SaveChangesAsync();
                //int id = sale.SaleId;
                if (sale.SaleDetails != null)
                {
                    decimal _quantities = sale.SaleDetails.Sum(s => s.Quantity);
                    if (_quantities > 0)
                    {
                        foreach (var detail in sale.SaleDetails)
                        {
                            if (detail.Quantity > 0)
                            {
                                //detail.SaleId = id;
                                Product product = await _context.Products.FirstOrDefaultAsync(d => d.ProductId == detail.ProductId);

                                detail.UserId = User.Identity.Name;
                                detail.UnitPrice = product.UnitPrice;
                                decimal _totalNoItbis = (detail.Quantity * detail.UnitPrice) - detail.Discount;
                                detail.ITBIS = _totalNoItbis * (product.ITBIS / 100);
                                detail.Total = _totalNoItbis + detail.ITBIS;

                                //product.UnitsInStock = product.UnitsInStock - detail.Quantity;

                                sale.Quantity = sale.Quantity + detail.Quantity;
                                sale.Discount = sale.Discount + detail.Discount;
                                sale.TotalNoITBIS = sale.TotalNoITBIS + _totalNoItbis;
                                sale.ITBIS = sale.ITBIS + detail.ITBIS;
                                sale.Total = sale.Total + detail.Total;

                                //_context.Update(product);
                                //_context.Add(detail);
                            }
                        }
                        if (sale.PaidTotal)
                        {
                            sale.Paid = sale.Total;
                            sale.Debt = 0;
                        }
                        else
                        {
                            sale.Debt = sale.Total - sale.Paid;
                        }
                        //_context.SaleDetails.AddRange(details);
                        _context.Sales.Add(sale);
                        Balance balance = await _context.Balances.FirstOrDefaultAsync(d => d.PaymentType == sale.PaymentType);
                        balance.Total += sale.Paid;
                        _context.Update(balance);
                        await _context.SaveChangesAsync();
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers.Where(c => c.StatusCustomer == Models.Enum.StatusCustomer.Activo).OrderBy(c => c.CustomerName), "CustomerId", "CustomerName", sale.CustomerId);
            ViewData["SalesPersonId"] = new SelectList(_context.SalesPersons.Where(s => s.StatusSalesPerson == Models.Enum.StatusSalesPerson.Activo).OrderBy(s => s.SalesPersonName), "SalesPersonId", "SalesPersonName", sale.SalesPersonId);
            ViewData["SaleId"] = sale.SaleId;
            return View(sale);
        }

        public IActionResult SaleDetailsCreate(int? i)
        {
            i--;
            ViewBag.i = i;

            ViewData["ProductId"] = new SelectList(_context.Products.Where(p => p.Category == Models.Enum.CategoryProduct.Helado || p.Category == Models.Enum.CategoryProduct.Sorbete).Where(s => s.StatusProduct == Models.Enum.StatusProduct.Activo).Select(s => new { ProductId = s.ProductId, ProductName = s.ProductName + " - " + EnumHelper<Models.Enum.Envase>.GetDisplayValue(s.Envase) + " - " + s.UnitPrice.ToString("C") }).OrderBy(o => o.ProductName), "ProductId", "ProductName", 0);

            return PartialView();
        }
    }
}

BCongelao/Views/SalesMD/Index.cshtml
@model IEnumerable<BCongelao.Models.Sale>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="SaleCreate">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SalesPerson)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SaleDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalNoITBIS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ITBIS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Debt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusSale)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SalesPerson.SalesPersonName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SaleDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalNoITBIS)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ITBIS)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Debt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusSale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    <a asp-controller="Sales" asp-action="Edit" asp-route-id="@item.SaleId">Edit</a> |
                    <a asp-controller="Sales" asp-action="Details" asp-route-id="@item.SaleId">Details</a> |
                    <a asp-controller="Sales" asp-action="Delete" asp-route-id="@item.SaleId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BCongelao/Views/SalesMD/SaleCreate.cshtml
@model BCongelao.Models.Sale

@{
    ViewData["Title"] = "SaleCreate";
}

<h2>SaleCreate</h2>

<h4>Sale</h4>

@using (Html.BeginForm("SaleCreate", "SalesMD", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SalesPersonId" class="control-label"></label>
                <select asp-for="SalesPersonId" class="form-control" asp-items="ViewBag.SalesPersonId"><option></option></select>
                <label style="font-weight:lighter;font-size: 0.8em;color: blue;">Seleccione el cliente o escriba el nombre, sino existe.</label>
                <br />
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"><option value="0"></option></select>

                <label asp-for="Customer.CustomerName" class="control-label"></label>
                <input asp-for="Customer.CustomerName" class="form-control" />

                <label asp-for="CustomerDescription" class="control-label"></label>
                <input asp-for="CustomerDescription" class="form-control" />
                <span asp-validation-for="CustomerDescription" class="text-danger"></span>

                <label asp-for="SaleDate" class="control-label"></label>
                <input asp-for="SaleDate" class="form-control" />
                <span asp-validation-for="SaleDate" class="text-danger"></span>

                <label asp-for="PaymentType" class="control-label"></label>
                <select asp-for="PaymentType" class="form-control" asp-items="Html.GetEnumSelectList<BCongelao.Models.Enum.PaymentType>()"></select>
                <span asp-validation-for="PaymentType" class="text-danger"></span>

                <div class="form-group">
                    <label asp-for="Delivery" class="control-label"></label>
                    <input asp-for="Delivery" class="form-control" />
                    <span asp-validation-for="Delivery" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PaidTotal" class="control-label" style="display: inline;"></label>
                    <input asp-for="PaidTotal" />
                    |
                    <label asp-for="Paid" class="control-label" style="display: inline;"></label>
                    <input asp-for="Paid" class="form-control" style="display: inline; width: 50%;" />
                    <span asp-validation-for="Paid" class="text-danger"></span>
                </div>


            </div>
        </div>
    </div>
    <div id="partial"></div>
    <input type="button" value="New detail" id="Add" class="btn btn-default" />
    <input type="submit" value="Create" class="btn btn-default" />
}

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts{
    <script>
        var i = 1;
        $("#Add").click(function () {
            $.ajax({
                url: '/SalesMD/SaleDetailsCreate',
                //url: '/app/SalesMD/SaleDetailsCreate',
                data: { i: i },
                success: function (data) {
                    $("#partial").append(data);
                }
            })
            i++;
        });
        $("#CustomerId").change(function () {
            $("#Customer_CustomerName").val($("option:selected", $("#CustomerId")).text());
        });
    </script>
}

BCongelao/Views/SalesMD/SaleDetailsCreate.cshtml
@model BCongelao.Models.SaleDetail

@{
    int i = ViewBag.i == null ? 0 : ViewBag.i;
}

<div class="row">
    <div class="col-md-9">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        @*<label>Detail: @i</label>*@
        <div class="form-group">
            <p>
                <label class="control-label">(@i) Quantity:</label> @Html.TextBox(null, 1, null, new { @Name = "SaleDetails[" + i + "].Quantity", @class = "form-control", @style = "width: 15%; display: inline-block;" })
                <label class="control-label">Product:</label> @Html.DropDownList(null, ViewBag.ProductId, null, new { @Name = "SaleDetails[" + i + "].ProductId", @class = "form-control", @style = "width: 35%; display: inline-block;" })
                <label class="control-label">Discount:</label> @Html.TextBox(null, 0, null, new { @Name = "SaleDetails[" + i + "].Discount", @class = "form-control", @style = "width: 15%; display: inline-block;" })
                @*<b>Presentación:</b> @Html.DropDownList(null, ViewBag.EnvaseId, null, new { @Name = "SaleDetails[" + i + "].EnvaseId" })*@
            </p>
        </div>
    </div>
</div>